### ISSUE TITLE
Strings with a percent sign

### ISSUE THREAD

**Issue by jorenvo** [Alhadis/language-emacs-lisp#1]
There seems to be potential issue with the % sign in strings. In the following snippet:

![atom](https://cloud.githubusercontent.com/assets/10252581/19016748/84eb8bfc-8823-11e6-8e17-effe772bc3eb.png)

The grammar seems to consider this invalid as it colors both the percent sign and the closing double quote. In GNU Emacs (with emacs-lisp-mode) though this is not the case:

![emacs](https://cloud.githubusercontent.com/assets/10252581/19016750/8a2db2de-8823-11e6-8b8c-3c7ea8170b47.png)

The string "%" is a valid string in Emacs Lisp. I suppose this grammar tries to identify format specifications which is ofcourse fine but the issue is not every string will be passed to a function which will interpret format specifications.

I happened to run into this issue in one of my [commits][1]. As you can see I happen to use a string which ends in %" and it messes up the formatting on GitHub.

Let me know if there's any way I can help.

[1]: https://github.com/jorenvo/simple-mpc/commit/c920da63cc2c5cbc56fb8eb87f260dfffba163f9#diff-eb17dc9700b61c804ff0d2bb15a2525cL63

**Comment by Alhadis** [comment]
\*sigh* It seemed like a good idea at the time... :S I can partly attribute this to having only a modest understanding of Lisp, so I'll remove it.

Well, not remove altogether. More like limit it only to functions that use `%` to introduce formatting indicators.

**Comment by Alhadis** [comment]
@jorenvo Am I right to believe [these](https://www.gnu.org/software/emacs/manual/html_node/elisp/Formatting-Strings.html) are the only Emacs functions where a `%` in a string has special significance...?

	error
	format
	format-message
	message

If not, please let me know what I'm missing.

**Comment by jorenvo** [comment]
Looking through the Emacs Lisp Reference Manual, those do indeed seem to be all of them.

**Comment by Alhadis** [comment]
Great! Thanks. =)

I've nearly finished with this; just smoothing out some wrinkles now. With the last remaining wrinkle being an issue with empty lines (which includes whitespace):

<img src="https://cloud.githubusercontent.com/assets/2346707/19019064/25bea848-88c4-11e6-8672-f6e91ebed479.png" width="247" alt="Figure 1" />

I'll cut a patch-release once I'm done, but the changes won't take effect on the site until the next release of [Linguist](https://github.com/github/linguist), which is the program responsible for selecting the highlighting grammars on the site.

**Comment by jorenvo** [comment]
Excellent, thank you for handling this so quickly!

**Comment by Alhadis** [comment]
No problem at all. =) Thanks for bringing it to my attention.

Issue resolved and patch released.
