### ISSUE TITLE
Muse: any block markup should stop list parsing

### ISSUE THREAD

**Issue by link2xt** [Alhadis/language-emacs-lisp#11]
For example, the second line here is a verse:
```
 - foo
> bar
```

Currently it is highlighted as paragraph.

**Comment by Alhadis** [comment]
Just to confirm: a verse's `>` *must* be in the first column, yes? It's not possible to nest verses inside, say, lists?

~~~
 - Text
   > verse
   Text
~~~

I wasn't sure if leading whitespace was allowed, so I [purposefully added it](https://github.com/Alhadis/language-emacs-lisp/blob/5012f075bc5d87883384b80eb56fb0892979cfdc/grammars/muse.cson#L840-L848) to avoid being too restrictive. But going from `bemuse`'s output, I think that was probably a mistake...

**Comment by link2xt** [comment]
Pandoc allows nesting verse like in your example. Text::Amuse doesn't, but it is a limitation due to the problems with conversion to LaTeX.

**Comment by Alhadis** [comment]
I'll leave things the way they are then.

Have regenerated the token snapshot for [`./spec/fixtures/input/block-verse.muse`](https://github.com/Alhadis/language-emacs-lisp/blob/1cf02a62f27e97ffcf34a5e7a278c22083cfdb01/spec/fixtures/input/block-verse.muse), so I'll mark this as closed.
