### ISSUE TITLE
Muse: do not allow letters after closing "*"

### ISSUE THREAD

**Issue by link2xt** [Alhadis/language-emacs-lisp#6]
This is unclosed emphasis:

```
Foo *bar*x baz
```

This too:
```
Foo *bar*0 baz
```

**Comment by Alhadis** [comment]
I admit I was a bit confused by Muse's treatment of emphasis boundaries. Does it allow *any* character to follow a `*` or simply alphanumeric characters? That is to say, should I be matching this:

```regexp
/\*[^\s*]/
```

... or this?

```regexp
/\*[a-zA-Z0-9]/
```

Same question about literal code spans, too (`=*=`).

**Comment by link2xt** [comment]
Text::Amuse has refined and symmetric rules for this, they are the same in `pandoc`. Emacs Muse had some glitches like allowing whitespace before closing `*`: https://amusewiki.org/library/manual#toc40

Relevant quote is this:

>  The opening one must be preceded by something which is not an alphanumerical character (or at the beginning of the line) and followed by something which is not a space.

> The closing one must be preceded by something which is not a space, and followed by something which is not an alphanumerical character (or at the end of the line). 

For "alphanumeric" use `[[:alnum:]]`, not `[a-zA-Z0-9]` as there are languages other than English.

**Comment by Alhadis** [comment]
> For "alphanumeric" use [[:alnum:]], not [a-zA-Z0-9] as there are languages other than English.

Surprise, [GitHub's regexp](https://github.com/github/linguist/issues/3291) engine doesn't know that:

* [`[[:alnum:]]+`](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-text&grammar_format=cson&grammar_url=&grammar_text=scopeName%3A+"test"%0D%0Apatterns%3A+%5Bmatch%3A+"%5B%5B%3Aalnum%3A%5D%5D%2B"%2C+name%3A+"invalid.illegal"%5D&code_source=from-text&code_url=&code=Foo+bar+Путин+смотрит+baz+qux)
* [`[\w]+`](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-text&grammar_format=cson&grammar_url=&grammar_text=scopeName%3A+"test"%0D%0Apatterns%3A+%5Bmatch%3A+"%5C%5Cw%2B"%2C+name%3A+"invalid.illegal"%5D&code_source=from-text&code_url=&code=Foo+bar+Путин+смотрит+baz+qux)

In any case, you're wrong. `[[:alnum:]]` is a POSIX class which (most) regex engines interpret specifically as `[A-Za-z0-9]`. Unicode-aware engines usually treat `\w` as `[\p{Alpha}\p{Digit}]` or `\p{PosixAlnum}`. Neither of which are an option on GitHub, sadly.

**Comment by Alhadis** [comment]
Fixed in f0b35d4.
