### ISSUE TITLE
Muse: support underline

### ISSUE THREAD

**Issue by link2xt** [Alhadis/language-emacs-lisp#7]
Emacs Muse supported underline syntax:
```
This is _underlined_ text
```

Amusewiki removed it, mostly for the reason that there is no semantic difference between underline and emphasis and underline is usually a typewriter version of emphasis. But for syntax highlighting it may be worth to support both. Also, `pandoc` supports both Emacs Muse underline and Amusewiki extensions.

**Comment by Alhadis** [comment]
I'm getting weird-looking results in Emacs...

<img src="https://user-images.githubusercontent.com/2346707/66784703-ecabf980-ef26-11e9-8608-408ceed44b56.png" alt="Figure 1" />

What should I be using as a regex? You mentioned that Emacs Muse's handling of word boundaries was a little flaky...

[This is what I currently have.](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_format=cson&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-emacs-lisp%2Fmaster%2Fgrammars%2Fmuse.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-emacs-lisp%2Fmaster%2Fspec%2Ffixtures%2Finput%2Finline-underline.muse&code=)

**Comment by link2xt** [comment]
Shouldn't it work just the same way as single `*` works?

**Comment by Alhadis** [comment]
Never mind, the `muse-emphasis-1` face doesn't show underlines for TTYs, so the "italic" spans looked like ordinary text... 😀 Oops.
