### ISSUE TITLE
Muse: "===" is not code

### ISSUE THREAD

**Issue by link2xt** [Alhadis/language-emacs-lisp#9]
Currently `===foo bar=` is parsed as two code spans.

`===` should not be treated as markup at all, because opening `=` should be preceded by whitespace and followed by alphanumeric character. Otherwise, `<code>` tag should be used.

**Comment by Alhadis** [comment]
> `===` should not be treated as markup at all

Are you sure? Pandoc is telling me otherwise:

~~~console
$ echo '===foo bar=' | pandoc --from muse --to html
<p><code>==foo bar</code></p>
~~~

I'll fix the `===` though, that was an oversight on my part.

**Comment by link2xt** [comment]
That's right, `=` does not have to be followed by alphanumeric, because it is code. Just non-whitespace is ok, pandoc is correct here.

**Comment by link2xt** [comment]
> Sorry, I misunderstood.

You understood correctly, my statement in the first post about "should not be treated as markup at all" is wrong.

Btw, pandoc implementation is written by me. It is a good reference as I have wrote many testcases there, including round-trip tests, and tested each testcase with both Text::Amuse and Emacs Muse at the time of writing.
